baseURL = "https://oskar-anderson.github.io/my-internship-blog/"
title = "my internship blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Sirowa praktikablogi"
    description = "TTÜ praktika, Karl Oskar Anderson"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"
    custom_css = ["mycss.css"]
    picturepath = "/my-internship-blog/pictures/"

[Permalinks]
    post = "content/:filename/"